repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-check

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright
        additional_dependencies:
          - rich>=14.3.3
          - termcolor>=3.3.0
          - pytest>=9.0.2
