"""Tests for target_precompile_headers command."""

import subprocess
import sys
from pathlib import Path

import pytest

from cja.generator import configure


def _compile_block(content: str, output_suffix: str) -> str:
    """Return the build statement for an output, with line continuations joined."""
    statements = content.replace("$\n    ", "").split("\nbuild ")
    return next(
        stmt
        for stmt in statements
        if stmt.split(":")[0].endswith(output_suffix)
    )


def _write_project(source_dir: Path, cmake: str) -> None:
    source_dir.mkdir(exist_ok=True)
    (source_dir / "CMakeLists.txt").write_text(
        "cmake_minimum_required(VERSION 3.16)\nproject(pch C CXX)\n" + cmake
    )


def test_private_pch_is_built_and_included(tmp_path: Path) -> None:
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_library(mylib STATIC lib.cpp)\n"
        "target_precompile_headers(mylib PRIVATE pch.h <vector>)\n",
    )
    (source_dir / "lib.cpp").write_text("int f() { return 0; }\n")

    configure(source_dir, "build")

    wrapper = source_dir / "build/CMakeFiles/mylib.dir/cmake_pch.hxx"
    assert wrapper.read_text() == (
        f'/* generated by cja */\n\n#include "{source_dir / "pch.h"}"\n'
        "#include <vector>\n"
    )
    assert not (source_dir / "build/CMakeFiles/mylib.dir/cmake_pch.h").exists()
    content = (source_dir / "build.ninja").read_text()
    pch_block = _compile_block(content, "cmake_pch.hxx.gch")
    assert "cxx_pch $builddir/CMakeFiles/mylib.dir/cmake_pch.hxx" in pch_block
    obj_block = _compile_block(content, "mylib_lib.o")
    assert "-include $builddir/CMakeFiles/mylib.dir/cmake_pch.hxx" in obj_block
    assert "| $builddir/CMakeFiles/mylib.dir/cmake_pch.hxx.gch" in obj_block


def test_wrapper_not_rewritten_when_unchanged(tmp_path: Path) -> None:
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_executable(app main.cpp)\ntarget_precompile_headers(app PRIVATE pch.h)\n",
    )
    (source_dir / "main.cpp").write_text("int main() { return 0; }\n")

    configure(source_dir, "build")
    wrapper = source_dir / "build/CMakeFiles/app.dir/cmake_pch.hxx"
    mtime = wrapper.stat().st_mtime_ns
    configure(source_dir, "build")
    assert wrapper.stat().st_mtime_ns == mtime


def test_public_pch_propagates_to_consumers(tmp_path: Path) -> None:
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_library(mylib STATIC lib.cpp)\n"
        "target_precompile_headers(mylib PUBLIC pub.h INTERFACE iface.h PRIVATE priv.h)\n"
        "add_executable(app main.cpp)\n"
        "target_link_libraries(app PRIVATE mylib)\n",
    )
    (source_dir / "lib.cpp").write_text("int f() { return 0; }\n")
    (source_dir / "main.cpp").write_text("int main() { return 0; }\n")

    configure(source_dir, "build")

    lib_wrapper = (source_dir / "build/CMakeFiles/mylib.dir/cmake_pch.hxx").read_text()
    assert "pub.h" in lib_wrapper
    assert "priv.h" in lib_wrapper
    assert "iface.h" not in lib_wrapper
    app_wrapper = (source_dir / "build/CMakeFiles/app.dir/cmake_pch.hxx").read_text()
    assert "pub.h" in app_wrapper
    assert "iface.h" in app_wrapper
    assert "priv.h" not in app_wrapper


def test_pch_per_language_with_genex(tmp_path: Path) -> None:
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_executable(app main.cpp util.c)\n"
        "target_precompile_headers(app PRIVATE common.h "
        '"$<$<COMPILE_LANGUAGE:CXX>:<string>>")\n',
    )
    (source_dir / "main.cpp").write_text("int main() { return 0; }\n")
    (source_dir / "util.c").write_text("int g(void) { return 0; }\n")

    configure(source_dir, "build")

    c_wrapper = (source_dir / "build/CMakeFiles/app.dir/cmake_pch.h").read_text()
    cxx_wrapper = (source_dir / "build/CMakeFiles/app.dir/cmake_pch.hxx").read_text()
    assert "common.h" in c_wrapper
    assert "<string>" not in c_wrapper
    assert "common.h" in cxx_wrapper
    assert "#include <string>" in cxx_wrapper
    content = (source_dir / "build.ninja").read_text()
    util_block = _compile_block(content, "app_util.o")
    assert "-include $builddir/CMakeFiles/app.dir/cmake_pch.h" in util_block
    assert "cmake_pch.hxx" not in util_block
    main_block = _compile_block(content, "app_main.o")
    assert "-include $builddir/CMakeFiles/app.dir/cmake_pch.hxx" in main_block


def test_skip_precompile_headers_source_property(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_executable(app main.cpp other.cpp third.cpp)\n"
        "target_precompile_headers(app PRIVATE pch.h)\n"
        "set_source_files_properties(other.cpp PROPERTIES SKIP_PRECOMPILE_HEADERS ON)\n"
        "set_property(SOURCE third.cpp PROPERTY SKIP_PRECOMPILE_HEADERS ON)\n"
        "get_property(skip SOURCE third.cpp PROPERTY SKIP_PRECOMPILE_HEADERS)\n"
        'message(STATUS "skip=${skip}")\n',
    )
    for name in ("main.cpp", "other.cpp", "third.cpp"):
        (source_dir / name).write_text("int main() { return 0; }\n")

    configure(source_dir, "build")

    content = (source_dir / "build.ninja").read_text()
    assert "-include" in _compile_block(content, "app_main.o")
    assert "-include" not in _compile_block(content, "app_other.o")
    assert "-include" not in _compile_block(content, "app_third.o")
    assert "skip=ON" in capsys.readouterr().out


def test_disable_precompile_headers(tmp_path: Path) -> None:
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_executable(app1 main.cpp)\n"
        "target_precompile_headers(app1 PRIVATE pch.h)\n"
        "set_target_properties(app1 PROPERTIES DISABLE_PRECOMPILE_HEADERS ON)\n"
        "set(CMAKE_DISABLE_PRECOMPILE_HEADERS ON)\n"
        "add_executable(app2 main.cpp)\n"
        "target_precompile_headers(app2 PRIVATE pch.h)\n",
    )
    (source_dir / "main.cpp").write_text("int main() { return 0; }\n")

    configure(source_dir, "build")

    content = (source_dir / "build.ninja").read_text()
    assert "-include" not in content
    assert ".gch" not in content


def test_reuse_from(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_library(base STATIC base.cpp)\n"
        "target_precompile_headers(base PRIVATE pch.h)\n"
        "add_executable(app main.cpp)\n"
        "target_precompile_headers(app REUSE_FROM base)\n"
        "get_target_property(headers base PRECOMPILE_HEADERS)\n"
        'message(STATUS "headers=${headers}")\n',
    )
    (source_dir / "base.cpp").write_text("int f() { return 0; }\n")
    (source_dir / "main.cpp").write_text("int main() { return 0; }\n")

    configure(source_dir, "build")

    app_wrapper = (source_dir / "build/CMakeFiles/app.dir/cmake_pch.hxx").read_text()
    assert f'#include "{source_dir / "pch.h"}"' in app_wrapper
    assert f"headers={source_dir / 'pch.h'}" in capsys.readouterr().out


def test_pch_build_end_to_end(tmp_path: Path) -> None:
    """Sources only compile if the precompiled header was force-included."""
    source_dir = tmp_path / "src"
    _write_project(
        source_dir,
        "add_executable(app main.cpp util.c)\n"
        "target_precompile_headers(app PRIVATE pch.h)\n",
    )
    (source_dir / "pch.h").write_text("#define ANSWER 42\n")
    (source_dir / "util.c").write_text("int answer(void) { return ANSWER; }\n")
    (source_dir / "main.cpp").write_text(
        'extern "C" int answer(void);\n'
        "int main() { return answer() == ANSWER ? 0 : 1; }\n"
    )

    result = subprocess.run(
        [sys.executable, "-m", "cja", "run"],
        capture_output=True,
        text=True,
        cwd=source_dir,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert (source_dir / "build/CMakeFiles/app.dir/cmake_pch.hxx.gch").exists()
    assert (source_dir / "build/CMakeFiles/app.dir/cmake_pch.h.gch").exists()
