"""Ninja build file generator."""

import platform
import re
from dataclasses import dataclass, field
from pathlib import Path

from .ninja_syntax import Writer
from .parser import Command


@dataclass
class Executable:
    """An executable target."""
    name: str
    sources: list[str]


@dataclass
class BuildContext:
    """Context for processing CMake commands."""
    source_dir: Path
    build_dir: Path
    project_name: str = ""
    variables: dict[str, str] = field(default_factory=dict)
    executables: list[Executable] = field(default_factory=list)


def expand_variables(value: str, variables: dict[str, str]) -> str:
    """Expand ${VAR} references in a string."""
    def replace(match: re.Match[str]) -> str:
        var_name = match.group(1)
        return variables.get(var_name, "")

    return re.sub(r'\$\{(\w+)\}', replace, value)


def process_commands(commands: list[Command], ctx: BuildContext) -> None:
    """Process CMake commands and populate the build context."""
    for cmd in commands:
        args = [expand_variables(arg, ctx.variables) for arg in cmd.args]

        match cmd.name:
            case "cmake_minimum_required":
                pass  # Just acknowledge it

            case "project":
                if args:
                    ctx.project_name = args[0]
                    ctx.variables["PROJECT_NAME"] = args[0]
                    ctx.variables["CMAKE_PROJECT_NAME"] = args[0]

            case "set":
                if len(args) >= 2:
                    ctx.variables[args[0]] = " ".join(args[1:])
                elif len(args) == 1:
                    ctx.variables[args[0]] = ""

            case "add_executable":
                if len(args) >= 2:
                    ctx.executables.append(Executable(
                        name=args[0],
                        sources=args[1:]
                    ))

            case _:
                pass  # Ignore unknown commands for now


def generate_ninja(ctx: BuildContext, output_path: Path) -> None:
    """Generate ninja build file."""
    # Detect compiler
    cc = "cc"
    cxx = "c++"

    # Detect executable extension
    exe_ext = ".exe" if platform.system() == "Windows" else ""

    with open(output_path, "w") as f:
        n = Writer(f)

        n.comment("Generated by cninja")
        n.newline()

        # Variables
        n.variable("cc", cc)
        n.variable("cxx", cxx)
        n.newline()

        # Compile rules
        n.rule(
            "cc",
            command="$cc -MMD -MF $out.d -c $in -o $out",
            depfile="$out.d",
            description="CC $out",
        )
        n.newline()

        n.rule(
            "cxx",
            command="$cxx -MMD -MF $out.d -c $in -o $out",
            depfile="$out.d",
            description="CXX $out",
        )
        n.newline()

        # Link rules
        n.rule(
            "link",
            command="$cc $in -o $out",
            description="LINK $out",
        )
        n.newline()

        n.rule(
            "link_cxx",
            command="$cxx $in -o $out",
            description="LINK $out",
        )
        n.newline()

        # Generate build statements for each executable
        default_targets: list[str] = []

        for exe in ctx.executables:
            objects: list[str] = []
            uses_cxx = False

            for source in exe.sources:
                source_path = ctx.source_dir / source
                obj_name = Path(source).stem + ".o"
                objects.append(obj_name)

                # Determine if C or C++
                if source.endswith(('.cpp', '.cxx', '.cc', '.C')):
                    rule = "cxx"
                    uses_cxx = True
                else:
                    rule = "cc"

                # Use path to source
                n.build(obj_name, rule, str(source_path))

            # Link
            exe_name = exe.name + exe_ext
            link_rule = "link_cxx" if uses_cxx else "link"
            n.build(exe_name, link_rule, objects)
            n.newline()

            default_targets.append(exe_name)

        # Default target
        if default_targets:
            n.default(default_targets)


def configure(source_dir: Path, build_dir: Path) -> None:
    """Configure a CMake project and generate build.ninja."""
    cmake_file = source_dir / "CMakeLists.txt"
    if not cmake_file.exists():
        raise FileNotFoundError(f"CMakeLists.txt not found in {source_dir}")

    from .parser import parse_file

    commands = parse_file(cmake_file)

    ctx = BuildContext(
        source_dir=source_dir.resolve(),
        build_dir=build_dir.resolve(),
    )

    # Set up standard CMake variables
    ctx.variables["CMAKE_SOURCE_DIR"] = str(ctx.source_dir)
    ctx.variables["CMAKE_BINARY_DIR"] = str(ctx.build_dir)

    process_commands(commands, ctx)

    # Generate build.ninja
    build_dir.mkdir(parents=True, exist_ok=True)
    generate_ninja(ctx, build_dir / "build.ninja")

    print(f"-- Configuring done")
    print(f"-- Generated {build_dir / 'build.ninja'}")
