"""Ninja build file generator."""

import platform
import re
from dataclasses import dataclass, field
from pathlib import Path

from .ninja_syntax import Writer
from .parser import Command


@dataclass
class Library:
    """A library target."""
    name: str
    sources: list[str]
    is_static: bool = True


@dataclass
class Executable:
    """An executable target."""
    name: str
    sources: list[str]
    link_libraries: list[str] = field(default_factory=list)


@dataclass
class BuildContext:
    """Context for processing CMake commands."""
    source_dir: Path
    build_dir: Path
    project_name: str = ""
    variables: dict[str, str] = field(default_factory=dict)
    libraries: list[Library] = field(default_factory=list)
    executables: list[Executable] = field(default_factory=list)

    def get_library(self, name: str) -> Library | None:
        for lib in self.libraries:
            if lib.name == name:
                return lib
        return None

    def get_executable(self, name: str) -> Executable | None:
        for exe in self.executables:
            if exe.name == name:
                return exe
        return None


def expand_variables(value: str, variables: dict[str, str]) -> str:
    """Expand ${VAR} references in a string."""
    def replace(match: re.Match[str]) -> str:
        var_name = match.group(1)
        return variables.get(var_name, "")

    return re.sub(r'\$\{(\w+)\}', replace, value)


def process_commands(commands: list[Command], ctx: BuildContext) -> None:
    """Process CMake commands and populate the build context."""
    for cmd in commands:
        args = [expand_variables(arg, ctx.variables) for arg in cmd.args]

        match cmd.name:
            case "cmake_minimum_required":
                pass  # Just acknowledge it

            case "project":
                if args:
                    ctx.project_name = args[0]
                    ctx.variables["PROJECT_NAME"] = args[0]
                    ctx.variables["CMAKE_PROJECT_NAME"] = args[0]

            case "set":
                if len(args) >= 2:
                    ctx.variables[args[0]] = " ".join(args[1:])
                elif len(args) == 1:
                    ctx.variables[args[0]] = ""

            case "add_library":
                if len(args) >= 2:
                    name = args[0]
                    # Check for STATIC/SHARED keyword
                    sources = args[1:]
                    is_static = True
                    if sources and sources[0] in ("STATIC", "SHARED"):
                        is_static = sources[0] == "STATIC"
                        sources = sources[1:]
                    ctx.libraries.append(Library(
                        name=name,
                        sources=sources,
                        is_static=is_static,
                    ))

            case "add_executable":
                if len(args) >= 2:
                    ctx.executables.append(Executable(
                        name=args[0],
                        sources=args[1:]
                    ))

            case "target_link_libraries":
                if len(args) >= 2:
                    target_name = args[0]
                    libs = args[1:]
                    # Skip visibility keywords
                    libs = [l for l in libs if l not in ("PUBLIC", "PRIVATE", "INTERFACE")]
                    exe = ctx.get_executable(target_name)
                    if exe:
                        exe.link_libraries.extend(libs)

            case _:
                pass  # Ignore unknown commands for now


def generate_ninja(ctx: BuildContext, output_path: Path, builddir: str) -> None:
    """Generate ninja build file."""
    # Detect compiler
    cc = "cc"
    cxx = "c++"

    # Detect extensions
    exe_ext = ".exe" if platform.system() == "Windows" else ""
    lib_ext = ".lib" if platform.system() == "Windows" else ".a"

    with open(output_path, "w") as f:
        n = Writer(f)

        n.comment("Generated by cninja")
        n.newline()

        # Variables
        n.variable("builddir", builddir)
        n.variable("cc", cc)
        n.variable("cxx", cxx)
        n.variable("ar", "ar")
        n.newline()

        # Compile rules
        n.rule(
            "cc",
            command="$cc -MMD -MF $out.d -c $in -o $out",
            depfile="$out.d",
            description="CC $out",
        )
        n.newline()

        n.rule(
            "cxx",
            command="$cxx -MMD -MF $out.d -c $in -o $out",
            depfile="$out.d",
            description="CXX $out",
        )
        n.newline()

        # Archive rule for static libraries
        n.rule(
            "ar",
            command="$ar rcs $out $in",
            description="AR $out",
        )
        n.newline()

        # Link rules
        n.rule(
            "link",
            command="$cc $in -o $out",
            description="LINK $out",
        )
        n.newline()

        n.rule(
            "link_cxx",
            command="$cxx $in -o $out",
            description="LINK $out",
        )
        n.newline()

        # Track library outputs for linking
        lib_outputs: dict[str, str] = {}

        # Generate build statements for libraries
        for lib in ctx.libraries:
            objects: list[str] = []

            for source in lib.sources:
                obj_name = f"$builddir/{lib.name}_{Path(source).stem}.o"
                objects.append(obj_name)

                # Determine if C or C++
                if source.endswith(('.cpp', '.cxx', '.cc', '.C')):
                    rule = "cxx"
                else:
                    rule = "cc"

                n.build(obj_name, rule, source)

            # Create static library
            if lib.is_static:
                lib_name = f"$builddir/lib{lib.name}{lib_ext}"
                n.build(lib_name, "ar", objects)
                n.newline()
                lib_outputs[lib.name] = lib_name

        # Generate build statements for executables
        default_targets: list[str] = []

        for exe in ctx.executables:
            objects: list[str] = []
            uses_cxx = False

            for source in exe.sources:
                obj_name = f"$builddir/{exe.name}_{Path(source).stem}.o"
                objects.append(obj_name)

                # Determine if C or C++
                if source.endswith(('.cpp', '.cxx', '.cc', '.C')):
                    rule = "cxx"
                    uses_cxx = True
                else:
                    rule = "cc"

                n.build(obj_name, rule, source)

            # Add linked libraries to inputs
            link_inputs = objects.copy()
            for lib_name in exe.link_libraries:
                if lib_name in lib_outputs:
                    link_inputs.append(lib_outputs[lib_name])

            # Link
            exe_name = f"$builddir/{exe.name}{exe_ext}"
            link_rule = "link_cxx" if uses_cxx else "link"
            n.build(exe_name, link_rule, link_inputs)
            n.newline()

            default_targets.append(exe_name)

        # Default target
        if default_targets:
            n.default(default_targets)


def configure(source_dir: Path, build_dir: str) -> None:
    """Configure a CMake project and generate build.ninja.

    Args:
        source_dir: Path to source directory containing CMakeLists.txt
        build_dir: Relative path for build directory (e.g., "build")
    """
    source_dir = source_dir.resolve()
    cmake_file = source_dir / "CMakeLists.txt"
    if not cmake_file.exists():
        raise FileNotFoundError(f"CMakeLists.txt not found in {source_dir}")

    from .parser import parse_file

    commands = parse_file(cmake_file)

    ctx = BuildContext(
        source_dir=source_dir,
        build_dir=source_dir / build_dir,
    )

    # Set up standard CMake variables
    ctx.variables["CMAKE_SOURCE_DIR"] = str(ctx.source_dir)
    ctx.variables["CMAKE_BINARY_DIR"] = str(ctx.build_dir)

    process_commands(commands, ctx)

    # Generate build.ninja in source directory
    output_path = source_dir / "build.ninja"
    generate_ninja(ctx, output_path, build_dir)

    # Create build directory
    ctx.build_dir.mkdir(parents=True, exist_ok=True)

    print(f"-- Configuring done")
    print(f"-- Generated {output_path}")
