name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: fedora:43

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: sudo dnf install -y uv python ninja gcc-c++ zlib-devel gtest-devel

    - name: Run tests
      run: uv run pytest --color=yes
