name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Install uv
    #   run: winget install --id=astral-sh.uv -e

    - name: Run tests
      run: uv run pytest
